### ISSUE TITLE
03 - Navigating the Map View

### ISSUE THREAD

**Issue by actzikas** [iworkscorp/18fpoc#1]
Title: Navigating the Map View 

---

ID: CATs_UC-03

---

BPMN Process: Map Navigation 

---

Related Use Case(s): N/A

---

Description: The General Public accesses the Food and Drug Administration’s Food Recall Geolocator page, and interacts with the map view to quickly navigate through the application. 

---

Actor(s): General Public

---

Precondition(s): Web application is running 

---

Main Success Scenario: 
1. User accesses the FDA’s webpage for geolocating food recalls
2. User clicks on a state in the U.S. map in which they want to look up recalls 
3. Webpage responds and displays the various food recalls in the selected state in a table
4. Use Case ends 

---

Extension(s): None 

---

Post Condition(s): Full information for the selected food recall is displayed 

---

Input Summary: U.S. State

---

Data Elements: 
• U.S. State
• Recall Status
• Recalling Firm
• Product Description
• Classification

---

Output Summary: N/A

---

Functional Requirements: **FR_001** The actor can quickly navigate information relevant to a geographical area by clicking on the map.

---

Business Rules: **BR_001** The actor can quickly find information relevant to their geographical area

**Comment by harjitdotsingh** [comment]
Done
