### ISSUE TITLE
Recall Status Drop Down Issue

### ISSUE THREAD

**Issue by FarazIzadi** [iworkscorp/18fpoc#13]
The values inside the 'Recall Status' drop-down are not fully visible when changing browser window to to different sizes. Please see attached screenshot.

**Comment by FarazIzadi** [comment]
![dropdownissue](https://cloud.githubusercontent.com/assets/12958071/8377599/8450da7c-1be0-11e5-829c-fe7120999c85.png)

**Comment by harjitdotsingh** [comment]
Done
