### ISSUE TITLE
Product Description and Recalling Firm

### ISSUE THREAD

**Issue by FarazIzadi** [iworkscorp/18fpoc#15]
These two bullet points under 'Reading Your Results' have the same identical description. Please update them to say as follows: 
- Product Description: Brief description of the product being recalled.
- Recalling Firm: The firm that initiates a recall or, in the case of an FDA requested recall or FDA mandated recall, the firm that has primary responsibility for the manufacture and (or) marketing of the product to be recalled.

Please see attached screenshot.

**Comment by FarazIzadi** [comment]
![proddesc](https://cloud.githubusercontent.com/assets/12958071/8378167/73d3bf3e-1be5-11e5-953f-6896027f38ac.png)

**Comment by harjitdotsingh** [comment]
Done
