### ISSUE TITLE
01 - Access Food Recall Tables

### ISSUE THREAD

**Issue by actzikas** [iworkscorp/18fpoc#2]
ID: CATs_UC-01

---

BPMN Process: Find Food Recalls 

---

Related Use Case(s): N/A

---

Description: The General Public accesses the Food and Drug Administration’s Food Recall Geolocator page, and uses the map view to quickly filter and find food recalls that affect them. 

---

Actor(s): General Public

---

Precondition(s): Recalls exist for the user’s state; web application is running 

---

Main Success Scenario:
1. User accesses the Food Recall Geolocator page 
2. Webpage will ask if they would like to share their location
3. User selects "yes" and the webpage will select the state they are in
4. Webpage displays the food recalls which have a distribution area in their state 
5. User clicks a row to get more information 
6. Webpage displays a window titled "Recall Details" which gives the user full details of the food recall
7. Use Case ends 

---

Alternate/Exceptional Flows: 
3A. If user selects "no" they will select a state from the map or from the drop down menu

---

Extension(s): None

---

Post Condition(s): Full information for the selected food recall is displayed

---

Input Summary: U.S. State

---

Data Elements:
- U.S. State 
- Recall Status 
- Recalling Firm 
- Product Description 
- Classification 
- Issue Date 
- Issue 
- UPC Code 
- Contact Information
- Recall Reason 

---

Output Summary: N/A

---

Functional Requirements: **FR_001** The actor can quickly find information relevant to their geographical area 

---

Business Rules: **BR_001** The actor can quickly find information relevant to their geographical area

**Comment by harjitdotsingh** [comment]
Done

**Comment by harjitdotsingh** [comment]
Issue has been closed
