### ISSUE TITLE
Scott's To Do's

### ISSUE THREAD

**Issue by scottrkerr** [iworkscorp/18fpoc#23]
- update narrative with link/reference to iAIM™ whitepaper
- resolve red comments on Attachment E document
- have Andrew transfer mockups from issue to .md file in repository

**Comment by harjitdotsingh** [comment]
Please make sure the changes are in master branch. The Dev branch had been tagged and a release has been cut... Unless we have made changed to developer branch I can then tag it again and cut a master branch.

Harjit

**Comment by scottrkerr** [comment]
Tasks completed
