### ISSUE TITLE
02 - Find FDA Food Recalls using Filter/Sort Functions

### ISSUE THREAD

**Issue by FarazIzadi** [iworkscorp/18fpoc#3]
**Title:** Find FDA Food Recalls using Filter/Sort Functions

---

**ID:** CATs_UC_02

---

**BPMN Process:** Using Filter/Sort Function to Narrow Down Results

---

**Related Use Case(s):** N/A

---

**Description:** The General Public accesses the Food and Drug Administration’s Food Recall Geolocator page, and uses the ‘Recall Status’ and filter functions to quickly find recalls that directly affect them.

---

**Actor(s):** General Public 

---

**Precondition(s):** Recalls exist for the user’s state; web application is running

---

**Main Success Scenario:**
1.  User accesses the FDA’s webpage for geolocating food recalls
2.  User can filter by 'State', 'Search', and 'Recall Status' 
3.  User filters recall status by ‘On-Going’, ‘Completed’, ‘Terminated’, or ‘Pending’
4.  User may also click on their state in the U.S. map
5.  Webpage displays a list of the food recalls which have a distribution area including the user’s state
6.     User can filter results by entering text in the 'filter by' free-text box
7. User can sort results by 'Recalling Firm' and 'Classification'
8.  Use Case ends

---

**Extensions:** None

---

**Post Condition(s)** Full information for filtered/sorted food recall is displayed

---

**Input Summary:**
- U.S. State

---

**Data Elements:**
• State
• On-Going
• Completed
• Terminated
• Pending
• Recalling Firm
• Product Description 
• Classification
• Filter By

---

**Output Summary:** Recall information specific to filtered/sorted data

---

**Functional Requirements:** **FR_001** The actor can quickly find information relevant to their geographical area

---

**Business Rules:** **BR_001** The actor can quickly find information relevant to their geographical area

**Comment by harjitdotsingh** [comment]
Done

**Comment by FarazIzadi** [comment]
Re-opening to update wording.
