### ISSUE TITLE
L on Geolocator needs to be lowercase 

### ISSUE THREAD

**Issue by actzikas** [iworkscorp/18fpoc#4]
![geolocator](https://cloud.githubusercontent.com/assets/12967253/8288005/6e6d8cd4-18e1-11e5-8be6-90ceb603e924.PNG)

**Comment by scottrkerr** [comment]
Please revise the title of the webpage to have the "L" on Geolocator to be lowercase.

**Comment by harjitdotsingh** [comment]
Done
