### ISSUE TITLE
Add a small description to the page to describe what the app does

### ISSUE THREAD

**Issue by scottrkerr** [iworkscorp/18fpoc#5]
Such as information how the app works, where the data comes from, etc

**Comment by harjitdotsingh** [comment]
Need the small Description...

**Comment by actzikas** [comment]
Welcome to the FDA's Food Recall Geolocator. The purpose of this application is to alert the general public with various food recalls in each state. To view recalls in this application do so by clicking on the map or selecting a state from the drop down menu. As a default your state is automatically selected when you enter the application. If you want to filter your search more, select from the Recall Status drop down. As a default, it is automatically set to display "ongoing" recalls in the selected area.

**Comment by harjitdotsingh** [comment]
Done
