### ISSUE TITLE
Reading Your Results! 

### ISSUE THREAD

**Issue by actzikas** [iworkscorp/18fpoc#7]
Please replace the title Classification to "Reading Your Results!" 

Class I: Dangerous or defective products that predictably could cause serious health problems or death. Examples include: food found to contain botulinum toxin, food with undeclared allergens, a label mix-up on a lifesaving drug, or a defective artificial heart valve.

Class II: Products that might cause a temporary health problem, or pose only a slight threat of a serious nature. Example: a drug that is under-strength but that is not used to treat life-threatening situations.

Class III: Products that are unlikely to cause any adverse health reaction, but that violate FDA labeling or manufacturing laws. Examples include: a minor container defect and lack of English labeling in a retail food.

**Comment by harjitdotsingh** [comment]
Done

**Comment by actzikas** [comment]
Please put a space between Class 1: Class 2: Class 3: and the description.

**Comment by actzikas** [comment]
above  Class I, Class II, Class III please also put the following descriptions: 

Product Description: Is a brief description of the product being recalled issued by the recalling firm. 
Recalling Firm: The firm that initiates a recall or, in the case of an FDA requested recall or FDA mandated recall, the firm that has primary responsibility for the manufacture and (or) marketing of the product to be recalled.

**Comment by harjitdotsingh** [comment]
Done
