### ISSUE TITLE
Interface Changes 

### ISSUE THREAD

**Issue by actzikas** [iworkscorp/18fpoc#8]
Please make the following changes to the webpage based on the suggestions from the meeting on 6/25. 
- Implement a color scheme similar to the site of Open.FDA.Gov 
- Work on the responsive design of the filter boxes
- Change the label of the search box in the table to "Filter"
- Readjust the spacing and alignment in the recall details box 
- Implement a theme in the table to make the columns more distinguishable 
- Change border colors on map - if applicable

**Comment by harjitdotsingh** [comment]
Done
