### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by FarazIzadi** [iworkscorp/18fpoc#9]
Please update the website with the following introduction:

**Welcome**

You have entered our interactive webpage that displays various Food Recalls in each state! This site was created in part of an open source project headed by open.fda.gov. Our mission is to provide the general public an interactive way to find food recalls in each state! How do you navigate the page? Just simply click on the map and the table will filter based on your search criteria! Want to learn more about a particular recall? Click on the row and a recall details window will pop up!

**Comment by harjitdotsingh** [comment]
Done
